forge:
  port: 8080
  context-path: "/"
  virtual-threads:
    enabled: true
    thread-name-prefix: "spring-vt-forge"
    max-concurrent-tasks: -1
    enable-metrics: true
    shutdown-timeout-ms: 10000

# Spring Boot configuration
spring:
  application:
    name: forge-spring-boot-example
  
  # Disable default web server since we're using our own
  main:
    web-application-type: none

logging:
  level:
    com.forge: DEBUG
    org.springframework: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"